#!/usr/bin/env bash
ob=${1%.*}
nopath=${1##*/}
npe=${nopath%.*}
jfile="$ob.j"
dist/build/compile/compile -c $1 -o "$jfile"
java -jar jasmin.jar $jfile
echo -e "#!/usr/bin/env bash\njava $npe" > $ob
chmod +x $ob